name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run UI tests
        run: npm run test:ui

      - name: Run API tests
        run: npm run test:api

      - name: Upload UI test report
        uses: actions/upload-artifact@v3
        with:
          name: ui-cucumber-report
          path: reports/ui-cucumber-report.json

      - name: Upload API test report
        uses: actions/upload-artifact@v3
        with:
          name: api-cucumber-report
          path: reports/api-cucumber-report.json